# See: https://circleci.com/docs/2.0/language-python/

version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.9.2

    steps:
      - checkout  # checkout source code to working directory

      - run:
          name: Install TeX
          command: |
            sudo apt-get update
            sudo apt-get install dvipng
            sudo apt-get install texlive texlive-latex-extra latexmk texlive-xetex

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip wheel setuptools
            pip install -r requirements/default.txt
            pip install -r requirements/doc.txt
            pip list

      - run:
          name: Install permute
          command: |
            source venv/bin/activate
            pip install -e .

      - run:
          name: Build docs
          command: |
            source venv/bin/activate
            make -C doc/ html
            #make -C doc/ latexpdf LATEXOPTS="-file-line-error -halt-on-error"
            #cp -a doc/build/latex/permute.pdf doc/build/html/.

      - store_artifacts:
          path: doc/build/html
